### PR TITLE
fixed responsiveness dyannamic title as weel as navigation

### PR DESCRIPTION
**Pull request by abhishekpanthee**
here you can see before and after comparison 

https://github.com/user-attachments/assets/80ea7a0c-b0aa-43d0-93a9-2a5519058e11

### CODE REVIEW

**Comment by abhishekpanthee** [comment]
Also if you could please assign the pr  gssoc-ext , hacktoberfest-accepted and level 2 or 3

**Comment by SaranshBangar** [comment]
@abhishekpanthee The responsive design looks good but please resolve the merge conflicts, ping me once you have done that and I will merge the PR

**Comment by abhishekpanthee** [comment]
@SaranshBangar  I think that resolved it

**Review by SaranshBangar — APPROVED** [review]
LGTM

**Pull request merged**
