### PR TITLE
Modified README.md file, Created dedicated Contributing.md file and LICENSE.

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
# Issue Resolved:

- Issue #67 

### 1) Added animated line separators and also Added GSSoC 2024 Extended & Hacktoberfest 2024 accepted banners:
image

### 2) Replaced the Contact section  with a **Team section**

- Before
image

- After
image

### 3) Updated the **Contributors Mention** section
image

### 4) Modified the **Contribution Guide** section:

- Before
image

- After
image
image

Also added a redirect to the **Contributing.md** file from the **README.md** file:
image

## 2. Added a dedicated **Contributing.md** file for the Contributors
image
image
image
image

## 3. Added MIT LICENSE
image

# Reference Video:

https://github.com/user-attachments/assets/e39c72d9-40a5-40a2-bc68-ac12f6b20795

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
Please review the PR and also assign the PR to me along with the necessary labels.
image

**Review by SaranshBangar — APPROVED** [review]
LGTM

**Comment by rajdeepchakraborty-rc** [comment]
> LGTM

I am sorry but I am a bit poor with short forms. Could you please say what you meant by this?

**Comment by rajdeepchakraborty-rc** [comment]
Also Please assign the PR to me.

**Comment by SaranshBangar** [comment]
> > LGTM
> 
> @SaranshBangar I am sorry but I am a bit poor with short forms. Could you please say what you meant by this?

No need to be sorry man, I meant 'Looks good to me' 😅

**Comment by rajdeepchakraborty-rc** [comment]
> > > LGTM
> > 
> > 
> > @SaranshBangar I am sorry but I am a bit poor with short forms. Could you please say what you meant by this?
> 
> No need to be sorry man, I meant 'Looks good to me' 😅

Oh. Thanks a lot for the appreciation. Hope you have a great day ahead 😄

**Pull request merged**
