### PR TITLE
added-xicon-navbar-#51

### PR DESCRIPTION
**Pull request by Athaxv**

### CODE REVIEW

**Comment by Athaxv** [comment]
hey can you please review it as all the checks are passed

**Review by SaranshBangar — COMMENTED** [review]
1. Lets wait for @jainaryan04 to complete it, if he is unable to do so, I'll merge this
2. Can you remove `heroicons` and instead use `react-icons` please

**Comment by Athaxv** [comment]
Ya sure, I will do add react-icons instead of heroicons

**Comment by Athaxv** [comment]
Can you add a hactober label to it too please

**Comment by SaranshBangar** [comment]
> Can you add a hactober label to it too please

I'll add all the labels at the time of merging the PR, you can check the previous PRs for confirmation

**Comment by SaranshBangar** [comment]
Issue resolved by another PR

**Pull request closed without merging**
