### PR TITLE
Email Validation | Email Service | Toast Alerts | Issue #91

### LINKED ISSUE #91: Newsletter Implementation | Email Validation | Toast Alerts Addition
I want to add the following features :-

1. Newsletter Implementation
2. Email Validation
3. Toast Alerts Addition 

https://github.com/user-attachments/assets/3eb4ff87-b6f7-429b-9105-911856c1c99e

@SaranshBangar Please assign this to me

### PR DESCRIPTION
**Pull request by Shariq2003**
fix #91 
I have added the following features :-

1. Newsletter Implementation
2. Email Validation
3. Toast Alerts Addition

https://github.com/user-attachments/assets/b7d1596c-3e16-41f1-b805-24499a85eed3

Completed #91

### CODE REVIEW

**Comment by Shariq2003** [comment]
@SaranshBangar please review my PR.

**Comment by Shariq2003** [comment]
@SaranshBangar please review and merge

**Review by SaranshBangar — CHANGES_REQUESTED** [review]
Please resolve the vercel deployment error

image

**Comment by Shariq2003** [comment]
> Please resolve the vercel deployment error
> 
> image

OKay fixing

**Comment by Shariq2003** [comment]
@SaranshBangar sir, please check now, i have fixed that error

**Comment by Shariq2003** [comment]
@SaranshBangar sir @MastanSayyad sir please review and merge this

**Review by MastanSayyad — APPROVED** [review]
@SaranshBangar If it requires merge this, giving labels till your response

**Review by SaranshBangar — APPROVED** [review]
LGTM

**Pull request merged**
