### PR TITLE
fixed carousal

### LINKED ISSUE #55: OverFlow of Testimonials cards
https://github.com/user-attachments/assets/f404174a-e6d3-40d1-bc06-b17be49a1a5a

### PR DESCRIPTION
**Pull request by ShivanshPlays**
The carousal was like:

https://github.com/user-attachments/assets/91a5c975-2c96-4c3e-8465-acf4b9479e2d

Problems:
1.It took too much time to reload
2.it was not in loop
3.it started abruptly from a  specific  point which was degrading ui
4. overall it was looking like bad ui

I have improved it and now it looks like:
 

https://github.com/user-attachments/assets/c061bd0b-0a14-4650-beb1-c482f8d3d791

closes #55

### CODE REVIEW

**Comment by ShivanshPlays** [comment]
@SaranshBangar can you please raise the level of this issue and pr from 1 to 2? It took an effort by my side setting it up

**Comment by ShivanshPlays** [comment]
@SaranshBangar please check

**Comment by ShivanshPlays** [comment]
@SaranshBangar bro please review

**Comment by ShivanshPlays** [comment]
@MastanSayyad  @SaranshBangar  It has been 4 days, this pr is pending, kindly merge or tell me if changes are needed.

**Comment by MastanSayyad** [comment]
Hi @SaranshBangar Program Manager this side, Please review this PR and merge it!

**Comment by ShivanshPlays** [comment]
@SaranshBangar  please merge, the deadline is close @MastanSayyad

**Comment by ShivanshPlays** [comment]
@sanjay-kv please review and merge sir, the deadline is close, thanks

**Review by MastanSayyad — APPROVED** [review]

**Pull request merged**
