### PR TITLE
added a new faq page

### PR DESCRIPTION
**Pull request by Sonuu20**
created a new modern faq page for the common related questions of the user and they could know the purpose of the application.

### CODE REVIEW

**Comment by Sonuu20** [comment]
@SaranshBangar Please approve this PR...

**Comment by SaranshBangar** [comment]
@Sonuu20 Please mention the issue number in the PR as well

**Comment by Sonuu20** [comment]
@SaranshBangar I've solved the issue of #94

**Review by SaranshBangar — APPROVED** [review]
LGTM

**Pull request merged**
