### PR TITLE
[FIX] Landing Page Overflow Fix

### LINKED ISSUE #44: [BUG] Landing Page Overflow
## Landing Page Overflow Issue
- Homepage shouldn't have any overflow.
- Nav bar links isn't working.

https://github.com/user-attachments/assets/eb6bac22-460d-467f-8d26-bec9aa7ded65

### PR DESCRIPTION
**Pull request by 4F24L**
## Overflow fixed
- Fixes #44 

https://github.com/user-attachments/assets/2fe385e3-8177-4bff-a79f-4132752fc74d

Would you please label this PR as level2  !!

### CODE REVIEW

**Review by SaranshBangar — CHANGES_REQUESTED** [review]
Please use Tailwind CSS instead of Vanilla CSS for the styling

**Comment by 4F24L** [comment]
Okay..

**Review by 4F24L — COMMENTED** [review]
tailwind css added

**Comment by 4F24L** [comment]
Hey @SaranshBangar , Please add labels to this PR !!

gssoc, level !!

**Comment by SaranshBangar** [comment]
@4F24L Done 👍🏼

**Pull request merged**
