### PR TITLE
Privacy Policy has been added to the Website which safeguards the sensitive informations of the users in the websites

### PR DESCRIPTION
**Pull request by ark0078**
I've created Privacy policy for Daneizo Website..Kindly check it please...am attaching the screenshots here.

Gave a similar layout too ...Issue #73 solved now
Screenshot (255)
Screenshot (256)

### CODE REVIEW

**Comment by ark0078** [comment]
@SaranshBangar kindly check and merge it...I hope this looks way cooler in your website..Hoping to contribute more in your project so that your project is successful..thanks for giving me this opportunity

**Review by SaranshBangar — APPROVED** [review]
LGTM

**Comment by ark0078** [comment]
@SaranshBangar thanks....

**Comment by ark0078** [comment]
@SaranshBangar can we get connected over email?

**Comment by SaranshBangar** [comment]
> @SaranshBangar can we get connected over email?

Sure, you can reach out to me at saranshbangad@gmail.com or we can connect on LinkedIn (https://www.linkedin.com/in/saransh-bangar/)

**Pull request merged**
