### PR TITLE
The footer UI changed 

### PR DESCRIPTION
**Pull request by jayanththalla**
The footer UI changed with symbols and icons
image

### CODE REVIEW

**Review by Himanshu-Sangshetti — APPROVED** [review]
Checked the PR @SaranshBangar, ready to merge.

**Comment by jayanththalla** [comment]
@Himanshu-Sangshetti can u label hacktoberfest accepted?

**Comment by jayanththalla** [comment]
@Himanshu-Sangshetti can u label hacktoberfest accepted?

**Comment by SaranshBangar** [comment]
@jayanththalla It is already added in the issue, we do not need to label it again

**Pull request merged**
