### PR TITLE
Added top rented page

### LINKED ISSUE #32: create a top rented page
I can create a top rented page where the most rented products are displayed.
The items will be hardcoded for now as there is no backend to this project....
Screenshot 2024-10-06 195252

Please assign me this issue under level2 gssoc gssoc-ext hacktoberfest hacktoberfest-accepted...I'll be happy to work on it 💯

PS: I have thoroughly visited all prs and issues assigned and I saw that there is already a backend PR (#18), 
when that is merged, 
I can raise another issue for the same top rented page and implement it fully along with the necessary changes in the backend, like schema and logic for calculating top rated products.

### PR DESCRIPTION
**Pull request by ShivanshPlays**
closes #32 

https://github.com/user-attachments/assets/7d4cdb56-3c4a-4414-8705-0cdc102d9578

### CODE REVIEW

**Review by SaranshBangar — CHANGES_REQUESTED** [review]
@ShivanshPlays The PR looks good, just do these 2 tasks

1. Change the filter background to something similar to the website
2. Resolve the deployment error
image

**Comment by ShivanshPlays** [comment]
oKAY I'm on it

**Comment by ShivanshPlays** [comment]
I have updated the bg but I am not able to grasp the vercel issue. can some mentor help me on this?
@SaranshBangar

**Comment by SaranshBangar** [comment]
@ShivanshPlays Just look into how to use `key` property in mapping

image

**Comment by ShivanshPlays** [comment]
@SaranshBangar Please check, the error is solved now

**Comment by ShivanshPlays** [comment]
@SaranshBangar please check

**Review by SaranshBangar — APPROVED** [review]
LGTM

**Pull request merged**
