### PR TITLE
Additon of All Contributors | Issue #25

### PR DESCRIPTION
**Pull request by Shariq2003**
I have added all the contributors in readme.md file to give them appreciation.
Completed #25 

image

@SaranshBangar please review and accept

### CODE REVIEW

**Review by SaranshBangar — APPROVED** [review]
LGTM

**Comment by Shariq2003** [comment]
> LGTM

?

**Comment by SaranshBangar** [comment]
> > LGTM
> 
> ?

"Looks good to me" 😅

**Comment by Shariq2003** [comment]
> > > LGTM
> > 
> > 
> > ?
> 
> "Looks good to me" 😅

😂, I thought I had messed up something.

**Pull request merged**
