### PR TITLE
Refactor login and signup pages

### PR DESCRIPTION
**Pull request by 0vai5**
This pull request refactors the login and signup pages. It updates the styling and layout of the forms, including the input fields and buttons. The changes improve the overall user experience and make the pages more visually appealing.

Closes Issue #77

### CODE REVIEW

**Comment by SaranshBangar** [comment]
@0vai5 Please mention which issue it resolves as well

**Comment by 0vai5** [comment]
> @0vai5 Please mention which issue it resolves as well

I have mentioned it in the pr description

**Comment by 0vai5** [comment]
Please merge PR @SaranshBangar

**Comment by 0vai5** [comment]
Please merge pr @SaranshBangar

**Review by SaranshBangar — APPROVED** [review]
LGTM

**Pull request merged**
